/* FITFORGE PRO — complete localStorage fitness tracker */
const workouts=[
{day:"Monday",title:"Chest + Triceps + Abs",cardio:"Treadmill: 25–30 min incline walk",exercises:[["Chest Press","4 × 8–12","60–90 sec"],["Incline Dumbbell Press","3 × 8–12","60–90 sec"],["Cable / Machine Fly","3 × 12–15","45–60 sec"],["Triceps Pushdown","3 × 10–15","45–60 sec"],["Overhead Triceps Extension","3 × 10–12","45–60 sec"],["Cable Crunch","3 × 12–15","45 sec"],["Plank","3 × 30–45 sec","45 sec"],["Treadmill Incline Walk","25–30 min","Finish"]]},
{day:"Tuesday",title:"Back + Biceps + Abs",cardio:"Treadmill: 25–30 min",exercises:[["Lat Pulldown","4 × 8–12","60–90 sec"],["Seated Cable Row","4 × 8–12","60–90 sec"],["Chest-Supported Row","3 × 10–12","60–90 sec"],["Face Pulls","3 × 12–15","45–60 sec"],["Dumbbell Curls","3 × 10–12","45–60 sec"],["Hammer Curls","3 × 10–12","45–60 sec"],["Hanging Knee Raises","3 × 10–15","45 sec"],["Russian Twists","3 × 16–20","45 sec"],["Treadmill Brisk Walk","25–30 min","Finish"]]},
{day:"Wednesday",title:"Legs + Core",cardio:"Treadmill: 20–25 min easy incline walk",exercises:[["Leg Press","4 × 10–12","90 sec"],["Romanian Deadlift","3 × 8–12","90 sec"],["Leg Curl","3 × 10–15","60 sec"],["Leg Extension","3 × 10–15","60 sec"],["Calf Raises","4 × 12–15","45–60 sec"],["Plank","3 × 30–60 sec","45 sec"],["Reverse Crunch","3 × 12–15","45 sec"],["Dead Bug","3 × 10 each side","45 sec"],["Treadmill Easy Incline Walk","20–25 min","Finish"]]},
{day:"Thursday",title:"Shoulders + Chest + Abs",cardio:"Treadmill: 30 min incline walk",exercises:[["Shoulder Press","4 × 8–12","60–90 sec"],["Lateral Raises","4 × 12–15","45–60 sec"],["Rear-Delt Fly","3 × 12–15","45–60 sec"],["Incline Chest Press","3 × 8–12","60–90 sec"],["Cable Fly","3 × 12–15","45–60 sec"],["Cable Crunch","3 × 12–15","45 sec"],["Side Plank","3 × 30 sec each side","45 sec"],["Treadmill Incline Walk","30 min","Finish"]]},
{day:"Friday",title:"Full Body + Abs",cardio:"Treadmill: 30–40 min",exercises:[["Leg Press","3 × 10","60–90 sec"],["Chest Press","3 × 10","60–90 sec"],["Lat Pulldown","3 × 10","60–90 sec"],["Seated Row","3 × 10","60–90 sec"],["Shoulder Press","3 × 10","60 sec"],["Biceps Curl","2 × 12","45–60 sec"],["Triceps Pushdown","2 × 12","45–60 sec"],["Hanging Knee Raises","3 × 10–15","45 sec"],["Bicycle Crunch","3 × 20","45 sec"],["Plank","3 × 45–60 sec","45 sec"],["Treadmill Cardio","30–40 min","Finish"]]}
].map(w=>({...w,exercises:w.exercises.map(e=>({name:e[0],sets:e[1],rest:e[2]}))}));
const meals=[['07:00','Breakfast','3 eggs + oats + banana'],['10:30','Morning Snack','Fruit + Greek yogurt or cottage cheese'],['13:00','Lunch','150–200g chicken + rice or potatoes + vegetables'],['16:30','Pre-Workout','Banana + Greek yogurt OR a small chicken/tuna sandwich'],['19:00','Dinner','150–200g lean protein + vegetables + moderate rice or potato'],['Optional','Evening Snack','Greek yogurt, cottage cheese, eggs or fruit']].map(x=>({time:x[0],name:x[1],food:x[2]}));
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}, save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const dateKey=(d=new Date())=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const todayKey=()=>dateKey(); const mondayOfWeek=()=>{const d=new Date();const n=d.getDay();d.setDate(d.getDate()-(n===0?6:n-1));d.setHours(0,0,0,0);return d};
let activeWorkout=Math.max(0,Math.min(4,new Date().getDay()-1));

/* WORKOUTS + DAILY COMPLETION + WEIGHT/REPS */
function exerciseKey(day,i){return `ff-complete-${todayKey()}-${day}-${i}`}
function completed(day,i){return localStorage.getItem(exerciseKey(day,i))==='1'}
function setCompleted(day,i,val){val?localStorage.setItem(exerciseKey(day,i),'1'):localStorage.removeItem(exerciseKey(day,i));updateWorkoutProgress(day);renderWeekly();updateStreaks();renderAchievements()}
function createWorkoutTabs(){const el=$('#dayTabs');el.innerHTML='';workouts.forEach((w,i)=>{const b=document.createElement('button');b.className='tab'+(i===activeWorkout?' active':'');b.textContent=w.day;b.onclick=()=>{activeWorkout=i;createWorkoutTabs();displayWorkout(i)};el.appendChild(b)})}
function getExerciseHistory(name){return load('ff-strength-'+name,[])}
function logStrength(name,weight,reps,sets){if(!weight&&!reps)return;const h=getExerciseHistory(name);h.push({date:todayKey(),weight:Number(weight)||0,reps:Number(reps)||0,sets:Number(sets)||0,t:Date.now()});save('ff-strength-'+name,h.slice(-30));renderStrengthProgress();renderAchievements()}
function displayWorkout(index){const w=workouts[index],p=$('#workoutPanel');p.innerHTML=`<div class="workout-title"><div><p class="eyebrow">${w.day.toUpperCase()}</p><h3>${w.title}</h3></div><span>${w.cardio}</span></div><div class="daily-workout-progress"><div class="workout-progress-info"><div><span>DAILY WORKOUT PROGRESS</span><p id="workoutProgressText"></p></div><strong id="workoutPercentage">0%</strong></div><div class="workout-progress-track"><div id="workoutProgressBar" class="workout-progress-bar"></div></div></div>`;
 w.exercises.forEach((e,i)=>{const h=getExerciseHistory(e.name),last=h.at(-1);const row=document.createElement('label');row.className='exercise';row.innerHTML=`<input type="checkbox" ${completed(w.day,i)?'checked':''}><div><h4>${e.name}</h4><p>Controlled reps • Rest ${e.rest}</p></div><strong>${e.sets}</strong><div class="exercise-log"><input class="log-weight" type="number" min="0" step="0.5" placeholder="Weight kg"><input class="log-reps" type="number" min="0" placeholder="Reps"><input class="log-sets" type="number" min="0" placeholder="Sets"><button type="button" class="btn ghost small log-btn">Save set</button><span class="last-log">${last?`Last: ${last.weight||'—'} kg × ${last.reps||'—'} reps × ${last.sets||'—'} sets (${last.date})`:'No strength log yet'}</span></div>`;row.querySelector('input[type=checkbox]').onchange=ev=>setCompleted(w.day,i,ev.target.checked);row.querySelector('.log-btn').onclick=ev=>{ev.preventDefault();const weight=row.querySelector('.log-weight').value,reps=row.querySelector('.log-reps').value,sets=row.querySelector('.log-sets').value;logStrength(e.name,weight,reps,sets);displayWorkout(index)};p.appendChild(row)});updateWorkoutProgress(w.day)}
function updateWorkoutProgress(day){const w=workouts.find(x=>x.day===day);const done=w.exercises.filter((_,i)=>completed(day,i)).length,p=Math.round(done/w.exercises.length*100);$('#workoutPercentage').textContent=p+'%';$('#workoutProgressBar').style.width=p+'%';$('#workoutProgressText').textContent=`${done} of ${w.exercises.length} exercises completed`;if(p===100){const dates=load('ff-complete-days',[]);if(!dates.includes(todayKey())){dates.push(todayKey());save('ff-complete-days',dates)}}}

/* WEEKLY PROGRESS + STREAK */
function dayPercent(w,date){let n=0;w.exercises.forEach((_,i)=>{if(localStorage.getItem(`ff-complete-${dateKey(date)}-${w.day}-${i}`)==='1')n++});return Math.round(n/w.exercises.length*100)}
function renderWeekly(){const start=mondayOfWeek(),box=$('#weeklyBars');box.innerHTML='';let done=0,total=0;workouts.forEach((w,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const pct=dayPercent(w,d);const count=Math.round(pct/100*w.exercises.length);done+=count;total+=w.exercises.length;box.insertAdjacentHTML('beforeend',`<div class="week-row"><span>${w.day}</span><div class="week-track"><i style="width:${pct}%"></i></div><strong>${pct}%</strong></div>`)});const pct=total?Math.round(done/total*100):0;$('#weeklyPercent').textContent=pct+'%';$('#weekAdherence').textContent=pct+'%';$('#weeklyCount').textContent=`${done} of ${total} exercises completed`}
function updateStreaks(){const dates=[...new Set(load('ff-complete-days',[]))].sort();let best=0,run=0,prev=null;dates.forEach(s=>{const d=new Date(s+'T00:00:00');if(prev&&Math.round((d-prev)/86400000)===1)run++;else run=1;best=Math.max(best,run);prev=d});let current=0;let cursor=new Date();for(let i=0;i<365;i++){const k=dateKey(cursor);if(dates.includes(k)){current++;cursor.setDate(cursor.getDate()-1)}else if(i===0){cursor.setDate(cursor.getDate()-1)}else break}$('#currentStreak').textContent=current;$('#bestStreak').textContent=best;save('ff-best-streak',Math.max(best,load('ff-best-streak',0)))}

/* REST TIMER */
let timerSeconds=60,timerRemaining=60,timerId=null;function paintTimer(){const m=Math.floor(timerRemaining/60),s=timerRemaining%60;$('#timerDisplay').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('#timerLabel').textContent=timerRemaining===0?'Rest complete — next set!':'Ready for your next set'}function setTimer(sec){clearInterval(timerId);timerId=null;timerSeconds=timerRemaining=sec;paintTimer()}$$('[data-seconds]').forEach(b=>b.onclick=()=>{$$('[data-seconds]').forEach(x=>x.classList.remove('active'));b.classList.add('active');setTimer(Number(b.dataset.seconds))});$('#timerStart').onclick=()=>{if(timerId||timerRemaining<=0)return;timerId=setInterval(()=>{timerRemaining--;paintTimer();if(timerRemaining<=0){clearInterval(timerId);timerId=null}},1000)};$('#timerPause').onclick=()=>{clearInterval(timerId);timerId=null};$('#timerReset').onclick=()=>setTimer(timerSeconds);

/* MEALS + PROTEIN + WATER */
function dailyState(name,def){return load(`ff-${name}-${todayKey()}`,def)}function setDaily(name,v){save(`ff-${name}-${todayKey()}`,v)}
function displayMeals(){const box=$('#mealList');box.innerHTML='';const state=dailyState('meals',{});meals.forEach((m,i)=>{const a=document.createElement('article');a.className='meal'+(state[i]?' completed':'');a.innerHTML=`<input type="checkbox" ${state[i]?'checked':''}><div><div class="meal-head"><h3>${m.name}</h3><span>${m.time}</span></div><p>${m.food}</p></div>`;a.querySelector('input').onchange=e=>{state[i]=e.target.checked;setDaily('meals',state);displayMeals();renderAchievements()};box.appendChild(a)})}
let water=dailyState('water',0),protein=dailyState('protein',0);function paintWater(){water=Math.min(4000,Math.max(0,water));$('#waterMl').textContent=water;const p=Math.min(100,Math.round(water/2500*100));$('#waterPercent').textContent=p+'% of target';$('#waterBar').style.width=p+'%'}$$('[data-water]').forEach(b=>b.onclick=()=>{water+=Number(b.dataset.water);setDaily('water',water);paintWater();renderAchievements()});$('#resetWater').onclick=()=>{water=0;setDaily('water',0);paintWater()};function paintProtein(){protein=Math.max(0,protein);$('#proteinCurrent').textContent=protein;const p=Math.min(100,Math.round(protein/160*100));$('#proteinPercent').textContent=p+'%';$('#proteinBar').style.width=p+'%'}$('#addProtein').onclick=()=>{const n=Number($('#proteinAmount').value);if(n>0){protein+=n;setDaily('protein',protein);$('#proteinAmount').value='';paintProtein();renderAchievements()}};$('#resetProtein').onclick=()=>{protein=0;setDaily('protein',0);paintProtein()};

/* TREADMILL */
let cardio=load('ff-cardio',[]);$('#treadmillForm').onsubmit=e=>{e.preventDefault();cardio.push({date:todayKey(),duration:Number($('#treadmillDuration').value),speed:Number($('#treadmillSpeed').value)||0,incline:Number($('#treadmillIncline').value)||0,distance:Number($('#treadmillDistance').value)||0,t:Date.now()});save('ff-cardio',cardio);e.target.reset();renderCardio();renderAchievements()};function renderCardio(){const start=mondayOfWeek().getTime(),week=cardio.filter(x=>new Date(x.date+'T00:00:00').getTime()>=start),mins=week.reduce((a,x)=>a+x.duration,0);$('#weeklyCardio').textContent=mins;$('#cardioTotal').textContent=mins;const box=$('#cardioHistory');box.innerHTML=cardio.length?'':'<p class="form-note">No treadmill sessions logged yet.</p>';cardio.slice(-6).reverse().forEach(x=>box.insertAdjacentHTML('beforeend',`<div class="history-item"><div><strong>${x.duration} min • ${x.speed||'—'} km/h</strong><small>${x.incline}% incline${x.distance?` • ${x.distance} km`:''}</small></div><small>${x.date}</small></div>`))}

/* WEIGHT + BMI + CANVAS TREND */
const startingWeight=105,goalWeight=98;let weightHistory=load('ff-weight-history',[]);function bmi(w,h){return w/((h/100)**2)}function updateProgress(){const last=weightHistory.at(-1),w=last?.weight||startingWeight,h=last?.height||165,change=w-startingWeight;$('#latestWeight').textContent=w.toFixed(1)+' kg';$('#weightChange').textContent=(change>0?'+':'')+change.toFixed(1)+' kg';$('#bmi').textContent=bmi(w,h).toFixed(1);const p=Math.max(0,Math.min(100,(startingWeight-w)/(startingWeight-goalWeight)*100));$('#goalBar').style.width=p+'%';$('#goalText').textContent=`${Math.round(p)}% of the way from ${startingWeight} kg to the first ${goalWeight} kg milestone.`;$('#dashboardWeight').innerHTML=`${w.toFixed(1)} <small>kg</small>`;$('#dashboardWeightChange').textContent=`${change.toFixed(1)} kg from start`;renderWeightHistory();drawWeightChart();renderAchievements()}
$('#weightForm').onsubmit=e=>{e.preventDefault();const w=Number($('#weight').value),h=Number($('#height').value);if(!w||!h)return;weightHistory.push({weight:w,height:h,date:todayKey(),t:Date.now()});save('ff-weight-history',weightHistory);$('#weight').value='';updateProgress()};$('#clearHistory').onclick=()=>{if(confirm('Clear weight history?')){weightHistory=[];localStorage.removeItem('ff-weight-history');updateProgress()}};
function renderWeightHistory(){const box=$('#history');box.innerHTML=weightHistory.length?'':'<p class="form-note">No weigh-ins logged yet.</p>';weightHistory.slice(-8).reverse().forEach(x=>box.insertAdjacentHTML('beforeend',`<div class="history-row"><span>${x.date}</span><strong>${x.weight.toFixed(1)} kg</strong><span>BMI ${bmi(x.weight,x.height).toFixed(1)}</span></div>`))}
function drawWeightChart(){const c=$('#weightChart'),ctx=c.getContext('2d'),d=weightHistory.slice(-12);ctx.clearRect(0,0,c.width,c.height);ctx.font='24px Arial';ctx.fillStyle='#9299a4';if(d.length<2){ctx.fillText('Log at least 2 weigh-ins to see your trend.',35,70);return}const vals=d.map(x=>x.weight),min=Math.min(...vals)-1,max=Math.max(...vals)+1,pad=50;ctx.strokeStyle='rgba(255,255,255,.10)';ctx.lineWidth=2;for(let i=0;i<4;i++){const y=pad+i*(c.height-pad*2)/3;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(c.width-pad,y);ctx.stroke()}ctx.strokeStyle='#c8ff3d';ctx.lineWidth=5;ctx.beginPath();d.forEach((x,i)=>{const px=pad+i*(c.width-pad*2)/(d.length-1),py=pad+(max-x.weight)/(max-min)*(c.height-pad*2);i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.stroke();ctx.fillStyle='#c8ff3d';d.forEach((x,i)=>{const px=pad+i*(c.width-pad*2)/(d.length-1),py=pad+(max-x.weight)/(max-min)*(c.height-pad*2);ctx.beginPath();ctx.arc(px,py,6,0,Math.PI*2);ctx.fill()})}

/* BODY MEASUREMENTS */
let measurements=load('ff-measurements',[]);$('#measurementForm').onsubmit=e=>{e.preventDefault();const entry={date:todayKey(),waist:Number($('#measureWaist').value)||0,chest:Number($('#measureChest').value)||0,arms:Number($('#measureArms').value)||0,thighs:Number($('#measureThighs').value)||0,hips:Number($('#measureHips').value)||0,t:Date.now()};if(!Object.values(entry).some(v=>typeof v==='number'&&v>0))return;measurements.push(entry);save('ff-measurements',measurements);e.target.reset();renderMeasurements();renderAchievements()};function renderMeasurements(){const x=measurements.at(-1),box=$('#measurementLatest');if(!x){box.innerHTML='<p class="form-note">No measurements logged yet.</p>';$('#measurementDate').textContent='No entries';return}$('#measurementDate').textContent=x.date;box.innerHTML=['waist','chest','arms','thighs','hips'].filter(k=>x[k]).map(k=>`<div><span>${k[0].toUpperCase()+k.slice(1)}</span><strong>${x[k]} cm</strong></div>`).join('')}

/* STRENGTH PROGRESSION */
function renderStrengthProgress(){const box=$('#strengthProgress');const names=[...new Set(workouts.flatMap(w=>w.exercises.map(e=>e.name)))];const cards=[];names.forEach(name=>{const h=getExerciseHistory(name);if(!h.length)return;const a=h.at(-1),b=h.at(-2),delta=b?a.weight-b.weight:0;cards.push(`<div class="strength-card"><span>${name}</span><strong>${a.weight||'—'} kg × ${a.reps||'—'}</strong><small>${b?(delta>0?'↑ +'+delta+' kg':delta<0?'↓ '+delta+' kg':'→ same weight'):'First log'}</small></div>`)});box.innerHTML=cards.length?cards.join(''):'<p class="form-note">Log weight and reps inside your workouts to see strength progression.</p>'}

/* ACHIEVEMENTS */
function totalStrengthLogs(){let n=0;[...new Set(workouts.flatMap(w=>w.exercises.map(e=>e.name)))].forEach(x=>n+=getExerciseHistory(x).length);return n}function renderAchievements(){const completedDays=load('ff-complete-days',[]).length,mealsDone=Object.values(dailyState('meals',{})).filter(Boolean).length;const defs=[['First Workout',completedDays>=1,'Complete a full workout'],['5 Workouts',completedDays>=5,'Complete five workout days'],['Perfect Week',Number($('#weeklyPercent')?.textContent.replace('%','')||0)>=95,'Reach 95% weekly adherence'],['Hydrated',water>=2500,'Reach 2.5 L today'],['Protein Target',protein>=130,'Reach at least 130 g today'],['Meal Discipline',mealsDone>=5,'Complete five meals today'],['Strength Logger',totalStrengthLogs()>=5,'Log five strength sets'],['Cardio 100',Number($('#weeklyCardio')?.textContent||0)>=100,'100 treadmill minutes this week'],['5 kg Down',(weightHistory.at(-1)?.weight||105)<=100,'Lose 5 kg from start'],['Measurements',measurements.length>=1,'Log body measurements']];const unlocked=defs.filter(x=>x[1]).length;$('#achievementCount').textContent=`${unlocked} unlocked`;$('#achievementList').innerHTML=defs.map(x=>`<div class="achievement ${x[1]?'unlocked':''}"><strong>${x[1]?'✓':'○'} ${x[0]}</strong><small>${x[2]}</small></div>`).join('')}

/* PROGRAM WEEK + NAV */
let start=localStorage.getItem('ff-program-start');if(!start){start=new Date().toISOString();localStorage.setItem('ff-program-start',start)}function programWeek(){const days=Math.floor((new Date()-new Date(start))/86400000);$('#weekNumber').textContent=Math.max(1,Math.min(12,Math.floor(days/7)+1))}
$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');$$('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));const sections=$$('main section[id]');function navSpy(){let current='dashboard';sections.forEach(s=>{if(scrollY>=s.offsetTop-180)current=s.id});$$('#nav a,.mobile-bottom-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current));$('#backToTop').classList.toggle('show',scrollY>500)}window.addEventListener('scroll',navSpy,{passive:true});$('#backToTop').onclick=()=>scrollTo({top:0,behavior:'smooth'});

function init(){createWorkoutTabs();displayWorkout(activeWorkout);displayMeals();paintWater();paintProtein();renderWeekly();updateStreaks();renderCardio();updateProgress();renderMeasurements();renderStrengthProgress();programWeek();renderAchievements();paintTimer();navSpy()}
init();
